name : Deploy React
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs :
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Commande npm install
        run: npm install
      - name: Commande predeploy
        run: npm run predeploy
      - name: Setup Pages
        id: pages
        uses: action/configure-pages@v3
      - name: Upload artifact
        uses: actions/unpload-pages-artifact@v2
        with:
          path: dist
          if-no-files-found: error
  deploy:
    environment:
      name: Github-pages
      url: ${{steps.deployement.output.page_url}}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
        
